### ISSUE TITLE
Frame not following bones

### ISSUE THREAD

**Issue by AbdallaGomaa** [alecjacobson/computer-graphics-kinematics#10]
![ezgif com-crop](https://user-images.githubusercontent.com/25573027/48678958-34c86d80-eb58-11e8-816e-88ed2b6fad29.gif)

I have the bones moving but the wireframe is not following the bones. Is there something I need to implement for this to happen?

**Comment by Kennnyoung** [comment]
it will happen after you implement linear_blending_skin
