### ISSUE TITLE
Forward kinematics aligned_allocator

### ISSUE THREAD

**Issue by chris-sky** [alecjacobson/computer-graphics-kinematics#11]
Hi I am not experienced in C++. Would anyone mind explaining what the Eigen::aligned_allocator<Eigen::Affine3d> in the input vector for forward_kinematics.cpp is for? I have read the documentation but I still do not understand how it should be used in this context. Thanks in advance!

**Comment by cheshmi** [comment]
That is for efficiency e.g., vectorization. You can assume it as a normal vector. You may look at the following link:
https://gist.github.com/donny-dont/1471329

**Comment by psarahdactyl** [comment]
https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html
