### ISSUE TITLE
Demos in the Readme

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-kinematics#12]
Hi Professor,

Just wondering, for the gifs you posted on the readme, are you using the same "exact" formula as the one given in the instructions? 
It seems that your models are able to produce a very very smooth movement.

**Comment by alecjacobson** [comment]
The gradient descent runs at one iteration per frame in debug mode. You might fiddle with this in main.cpp if you want to stay in debug mode. Otherwise in release mode you should see 100 iterations of gradient descent per frame. (I think IK smoothness  is what you're referring to)
