### ISSUE TITLE
random output

### ISSUE THREAD

**Issue by Kennnyoung** [alecjacobson/computer-graphics-kinematics#13]
Right now my output is very random, with same code, sometimes the animation behaves very well as expected, but sometimes the model will disappear in the end of animation. I am just curious what might cause this randomness?
Also a constant behaviour is when I run the executable, the first time animation will skip first couple key frames, but when I press R to reset it, first couple key frames will be played as normal every time. Any thoughts?

**Comment by Kennnyoung** [comment]
nvm, figured it out

**Comment by Panmani** [comment]
What was the issue? I am having the same problem.

**Comment by Kennnyoung** [comment]
The constant behaviour is normal, as soon as you run the executable the animation time begins counting, by the time you see the animation its already couple key frame after. When you reset the animation, the time gets reset as well, so you can see all key frames. The random one just when you do cat mull interpolation, you need to connect the tail of list of key frames with its head, otherwise the index will be out of bound, if you using [] to access the list, it wont be seg fault but reading junks that got stored in the index position. If you using .at() to access the item, should produce seg fault.
