### ISSUE TITLE
About Catmull-Rom-Interpolation

### ISSUE THREAD

**Issue by Xeroken** [alecjacobson/computer-graphics-kinematics#14]
I've read the Catmull-Rom-Interpolation page given in the assignment, but what are we supposed to do when calculating the tangents involving an interval having an endpoint within the data?

**Comment by Panmani** [comment]
Yeah, have the same problem here. How to get the tangent for the endpoints?

**Comment by cheshmi** [comment]
Those values should not be very important. However, there are different ways to set it to a certain value. You can search to find some of these assumptions.
