### ISSUE TITLE
Viewing other models?

### ISSUE THREAD

**Issue by Desmeister** [alecjacobson/computer-graphics-kinematics#18]
I'm working from the UG machines and the projects seems to compile and display properly, but I can't seem to switch the view to anything other than the default robot-arm model.

I see in the terminal that you can use "<,>" to switch models, but no key seems to work. All the other commands like toggle wireframe and switch to canonical view seem to function properly.

Is this implemented later in the lab or perhaps setup in a config file somewhere, or just an error?

**Comment by Desmeister** [comment]
Resolved: Edit line 41 on main with an the appropriate data json

**Comment by alecjacobson** [comment]
The .json is also accepted as a command line argument, so you shouldn't have to change the `main.cpp`.

(meanwhile, the `<,>` toggles between the skeleton mesh and the model's mesh)
