### ISSUE TITLE
stationary output

### ISSUE THREAD

**Issue by Madach97** [alecjacobson/computer-graphics-kinematics#19]
I implemented the functions until copy skeleton at and I find that I get no animation yet. The object is just stationary. Is this expected? I thought that after catmull-rom is should start having animation.
![capture](https://user-images.githubusercontent.com/25268627/48819205-c1bc2400-ed1c-11e8-84b4-c2cad7588109.JPG)

**Comment by nafis95** [comment]
it should start moving after Catmull Rom.

These are the functions used for Forward Kinematics (FK):
src/euler_angles_to_transform.cpp
src/forward_kinematics.cpp
src/catmull_rom_interpolation.cpp
//the above 3 will move the bones
src/linear_blend_skinning.cpp // to move the skin as well

note that src/transformed_tips.cpp function is used for IK and not FK, so its implementation wont affect FK
Not part of animation, but a general comment: your transformed tips function might have a bug. the circles should appear at the fingertips. this would cause issues in IK

**Comment by alecjacobson** [comment]
From the screenshot it looks like @Madach97  is in IK mode. Switch to animation mode by hitting `i` and restart the animation using `r`.
