### ISSUE TITLE
Equation 33 Readme

### ISSUE THREAD

**Issue by Marina-t** [alecjacobson/computer-graphics-kinematics#20]
Why are we using an addition here instead of a negation?
![equation33](https://user-images.githubusercontent.com/9604950/48827863-40748980-ed3c-11e8-8218-59836ccfc466.png)
thanks

**Comment by nafis95** [comment]
I had a similar question. For me negation worked and positive didnt work, so i just have that in my code.  Not sure why it mentions positive in the readme

**Comment by alecjacobson** [comment]
The readme is correct. ∆a is the step direction. What direction should this be if using gradient descent? That is, ∆a = ?

**Comment by ptanugra** [comment]
I think this is just a matter of notation. 
If the change in _a_ is negative as mentioned in the previous section, your equation would be then negative.
