### ISSUE TITLE
Failed to Start Project

### ISSUE THREAD

**Issue by CalinArdelean** [alecjacobson/computer-graphics-kinematics#26]
I cloned the repo from Git and ran cmake .. on Windows 10. I did no modifications to the original code.
I got an exception at line 86 in DenseStorage.h: EIGEN_MAKE_UNALIGNED_ARRAY_ASSERT(0xf);
How can I resolve this framework problem?

**Comment by abhimadan** [comment]
Can you provide a stack trace for this assertion failure (to see what part of the provided code is causing the issue), and the compiler you're using?

**Comment by CalinArdelean** [comment]
![image](https://user-images.githubusercontent.com/17633482/69013941-47d07200-0953-11ea-900a-7835f7601c22.png)


Assertion failed: (reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****", file d:\csc418\a7_2\libigl\external\eigen\eigen\src/Core/DenseStorage.h, line 86

![image](https://user-images.githubusercontent.com/17633482/69013925-23749580-0953-11ea-94f5-9315f90b0538.png)

**Comment by rarora7777** [comment]
This issue shouldn't appear in MSVC 14.2x (VS 2019). Can you update to VS 2019?

**Comment by CalinArdelean** [comment]
I updated to Visual Studio 2019 and it seems to work fine, although 2019 by default is set up for 64-bit configuration, but it still works.
