### ISSUE TITLE
How to check each function's correctness?

### ISSUE THREAD

**Issue by RioAraki** [alecjacobson/computer-graphics-kinematics#5]
Hey, in most previous assignments we can check the output after we have finished every or at least several functions. This time I noticed that this kind of intermediate output is not being provided. Right now I have finished some files but I am unable to tell if I did this correctly ( it compiled, but I may misinterpret some math equations or have other kind of issues) and I can see how hard it would be to debug or separate the problem if we can only see result  after finish everything. Thus, I am wondering if there is some plausible way to check each function's correctness?

**Comment by RioAraki** [comment]
I have finished src/catmull_rom_interpolation.cpp and all files before (4/10), so take catmull_rom_interpolation as an example, it would be great if we can have some sample input keyframes in data type of time and rotations and some query times. By given the answer we could find if our implementation is right or not. May something like this .. I mean it is a fair game since when working research or jobs no answer would not be given, but previous assignments have these and its really handy cuz it let you know you are on the right track.

**Comment by lcapacitor** [comment]
I agree. Also, is there a feasible way to check if the Jacobian matrix is correctly calculated?

**Comment by RioAraki** [comment]
Not really, it is a good idea to do so after finishing all functions and begin the testing

**Comment by alecjacobson** [comment]
I would do it _as_ you write the funcntions. Rather than at the end.

**Comment by lcapacitor** [comment]
Sorry, so what test data we need to create?

**Comment by RioAraki** [comment]
True, that's a standard test-driven programming process would do.
