### ISSUE TITLE
Model shaking when not moving the effectors endpoint

### ISSUE THREAD

**Issue by ptanugra** [alecjacobson/computer-graphics-kinematics#6]
Hi Professor, 

In IK mode, How can I fix the problem of certain models (particularly beast.json) shaking even when I'm not moving the effector end points? 
This is fine for other models such as chimpanzee-hands, robot-arm ..

Other than that, I can move the effectors around and the bone parts would follow around correctly

**Comment by alecjacobson** [comment]
I'd start by debugging your line-search/gradient descent. Print out your energy and make sure it's [monotonically](https://en.wikipedia.org/wiki/Monotonic_function) decreasing.
