### ISSUE TITLE
gradient calculation

### ISSUE THREAD

**Issue by zhtdavis** [alecjacobson/computer-graphics-kinematics#7]
Besides calculating the Jacobian matrix, it seems we still need to calculate the dE/dX vector. Do we apply the same trick to get dE/dX? i.e. add 10e-7 to the position vector and get the difference between the new E value and the old E value then divide by 10e-7.

Thanks in advance!

**Comment by lcapacitor** [comment]
Since E(x) = ||x-q||^2, then E'(x) = 2(x-q) ?
