### ISSUE TITLE
Cmake Error on Windows System

### ISSUE THREAD

**Issue by ghiacciozero** [alecjacobson/computer-graphics-kinematics#8]
I tried to use CMake on Windows, but I got an error in configuration process:
![1-1](https://user-images.githubusercontent.com/22648098/48677398-4f372280-eb29-11e8-9c7d-f478b4e634ff.PNG)
![1-2](https://user-images.githubusercontent.com/22648098/48677399-50684f80-eb29-11e8-8e5a-5c4a1dec085a.PNG)

**Comment by Madach97** [comment]
I have the same problem.

**Comment by psarahdactyl** [comment]
I can look into this

**Comment by alecjacobson** [comment]
We seemed to have fixed it: https://github.com/libigl/libigl/issues/1021

**Comment by avaxman** [comment]
I think that's exactly the issue I'm getting here:
https://github.com/libigl/libigl/issues/1102
