### ISSUE TITLE
How to properly run ./kinematics for animation?

### ISSUE THREAD

**Issue by Panmani** [alecjacobson/computer-graphics-kinematics#9]
As I understand it, the key "i" is used for toggling animation. But when I printed out the size of the parameter "keyframes" in "catmull_rom_interpolation.c", it is zero. Not sure what is wrong.

**Comment by alecjacobson** [comment]
Well you have to implement the tasks

**Comment by Panmani** [comment]
Yeah, I have implemented the first five files. Not sure whether I am toggling the animation correctly.

**Comment by ptanugra** [comment]
I suggest (if you haven't) going to main.cpp and figure out how all the files are interconnected and also see the parameters that are being passed to the function call

**Comment by WilsonWangTHU** [comment]
@Panmani some of the bones do not come with any keyframes, but the others have. I guess that is what you observed ;p

**Comment by Panmani** [comment]
Sorry, I figured it out. Thank you!
